// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateOrderRes interface {
	createOrderRes()
}

type DeleteOrderRes interface {
	deleteOrderRes()
}

type ListOrderRes interface {
	listOrderRes()
}

type ReadOrderRes interface {
	readOrderRes()
}

type UpdateOrderRes interface {
	updateOrderRes()
}
